services:
  back-service:
    image: back-service # Или любое другое имя вашего контейнера
    ports:
      - "3000:3000" # Разработчик ОБЯЗАН использовать порт 3000 внутри контейнера
    volumes:
      - ./shared_data:/shared_data
    networks:
      - new_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  dvizhenie:
    image: dvizhenie
    ports:
      - "4000:4000"
    volumes:
      - ./shared_data:/app/shared_data
    networks:
      - new_network
    depends_on:
      - back-service

networks:
  new_network:
    driver: bridge

volumes:
  shared_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./shared_data 